@baseUrl = http://0.0.0.0:8080/user
@baseUrl_2 = http://0.0.0.0:8080/advertisment

#Создание пользователя
POST {{baseUrl}}/
Content-Type: application/json

{
    "name": "te_d4544534545fdf22",
    "password": "fhhd4fdd",
    "email": "ts@iff3345443445d2l.com"
}

###

#Получение пользователя
GET {{baseUrl}}/1/

###

#Обновление пользователя
PATCH {{baseUrl}}/1/
Content-Type: application/json

{
    "name": "tets_4"
}

###

#Удаление пользователя
DELETE {{baseUrl}}/1/

###

#Создание объявления
POST {{baseUrl_2}}/
Content-Type: application/json

{
    "title": "test",
    "description": "test_2",
    "user_id": 1
}

###

#Получение объявления
GET {{baseUrl_2}}/1/

###

#Обновление объявления
PATCH {{baseUrl_2}}/1/
Content-Type: application/json

{
    "title": "test_5",
    "description": "test_100"
}

###

#Удаление объявления
DELETE {{baseUrl_2}}/1/